wallpaper {
  monitor = HDMI-A-1
  path = ~/Pictures/Wallpapers/snow.jpg
  fit_mode = cover
}
wallpaper {
  monitor = DVI-D-1
  path = ~/Pictures/Wallpapers/snow.jpg
  fit_mode = cover
}

splash = false
